const categories = [
  {
    id: "science",
    name: "Science",
    description: "Physics, Chemistry, Biology, and more",
    icon: "🧪",
    color: "bg-blue-500",
  },
  {
    id: "history",
    name: "History",
    description: "World history, events, and civilizations",
    icon: "📚",
    color: "bg-amber-500",
  },
  {
    id: "geography",
    name: "Geography",
    description: "Countries, capitals, and world knowledge",
    icon: "🌍",
    color: "bg-green-500",
  },
  {
    id: "technology",
    name: "Technology",
    description: "Programming, computers, and digital world",
    icon: "💻",
    color: "bg-purple-500",
  },
  {
    id: "general",
    name: "General Knowledge",
    description: "Mixed topics and trivia",
    icon: "🧠",
    color: "bg-gray-500",
  },
]

const quizQuestions = [
  {
    id: 1,
    question: "What is the capital of France?",
    options: ["London", "Berlin", "Paris", "Madrid"],
    correctAnswer: 2,
    explanation: "Paris is the capital and most populous city of France.",
    category: "geography",
  },
  {
    id: 2,
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    correctAnswer: 1,
    explanation: "Mars is called the Red Planet due to its reddish appearance caused by iron oxide on its surface.",
    category: "science",
  },
  {
    id: 3,
    question: "What is the largest mammal in the world?",
    options: ["African Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
    correctAnswer: 1,
    explanation:
      "The Blue Whale is the largest animal ever known to have lived on Earth, reaching lengths of up to 100 feet.",
    category: "science",
  },
  {
    id: 4,
    question: "In which year did World War II end?",
    options: ["1944", "1945", "1946", "1947"],
    correctAnswer: 1,
    explanation: "World War II ended in 1945 with the surrender of Japan in September.",
    category: "history",
  },
  {
    id: 5,
    question: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: 2,
    explanation: "Au is the chemical symbol for gold, derived from the Latin word 'aurum'.",
    category: "science",
  },
  {
    id: 6,
    question: "Which programming language was created by Brendan Eich?",
    options: ["Python", "JavaScript", "Java", "C++"],
    correctAnswer: 1,
    explanation: "JavaScript was created by Brendan Eich in 1995 while he was working at Netscape.",
    category: "technology",
  },
  {
    id: 7,
    question: "What is the smallest country in the world?",
    options: ["Monaco", "Nauru", "Vatican City", "San Marino"],
    correctAnswer: 2,
    explanation:
      "Vatican City is the smallest sovereign state in the world, with an area of approximately 0.17 square miles.",
    category: "geography",
  },
  {
    id: 8,
    question: "Which element has the atomic number 1?",
    options: ["Helium", "Hydrogen", "Lithium", "Carbon"],
    correctAnswer: 1,
    explanation: "Hydrogen has the atomic number 1, making it the lightest and most abundant element in the universe.",
    category: "science",
  },
  {
    id: 9,
    question: "What is extension of JavaScript ?",
    options: [".cpp", ".java", ".js", ".C"],
    correctAnswer: 3,
    explanation: "The extension of JavaScript is .js .",
    category: "technology",
  },
  {
    id: 10,
    question: "Which company produces the Windows operating System ?",
    options: ["Google LLC", "Microsoft Corporation", "Apple Inc.", "Oracle Corporation"],
    correctAnswer: 2,
    explanation: "Windows is a flagship product of Microsoft Corporation.",
    category: "technology",
  },
  {
    id: 11,
    question: "Who is the founder of Apple?",
    options: ["Steve Job", "Jackson Henry", "Phil Hughes", "Henry Smith"],
    correctAnswer: 1,
    explanation: "Apple Inc. was founded on April 1, 1997, by Steve Jobs .",
    category: "technology",
  },
  {
    id: 12,
    question: "How many bits is a byte ?",
    options: ["4", "8", "16", "32"],
    correctAnswer: 2,
    explanation: "8 bit = 1 Byte .",
    category: "technology",
  },
  {
    id: 13,
    question: "What does HTTP stands for ?",
    options: ["Hyper Text Transfer Protocol", "Hyper Text Transfer Plotter", "Head Tail Transfer Plot", "Head Tail Transfer Protocol"],
    correctAnswer: 1,
    explanation: "HTTP - Hyper Text Transfer Protocol .",
    category: "technology",
  },
  {
    id: 14,
    question: "What is primary purpose of a firewall in network ?",
    options: ["Virus scanning", "Data encryption", "Access control", "Device authentication"],
    correctAnswer: 3,
    explanation: " To monitor and control incoming & outcoming network traffic.",
    category: "technology",
  },
  {
    id: 15,
    question: "What does URL stand for?",
    options: ["Uniform Research Locator", "Uniform Resource Locator","Universal Resource Link", "Unique Routing Language"],
    correctAnswer: 2,
    explanation: "It's the address to access a resource on the internet .",
    category: "technology",
  },
  
  {
    id: 16,
    question: "Which gas is most abundant in Earth's atmosphere ?",
    options: ["Oxygen(O2)", "Carbon dioxide(CO2)","Hydrogen(H2)", "Nitrogen(N2)",],
    correctAnswer: 4,
    explanation: "About 78% of Earth's atmosphere is nitrogen.",
    category: "science",
  },
  {
    id: 17,
    question: "Who discovered the law of gravity ?",
    options: ["Isaac Newton","Albert Einstein", "Galileo Galilei",  "Nokola Tesla"],
    correctAnswer: 1,
    explanation: "He explainedd gravitational force after observing a falling apple",
    category: "science",
  },
  {
    id: 18,
    question: "What is the chemical symbol of Silver ?",
    options: ["Gd", "Ag", "Au", "go"],
    correctAnswer: 2,
    explanation: " From Latin word Argentum -meaning shiny or white .",
    category: "science",
  },
  {
    id: 19,
    question: "Which is the largest organ in the human body ?",
    options: ["Heart", "Liver", "Skin", "Brain"],
    correctAnswer: 3,
    explanation: "Skin covers the body and protects internal orgens .",
    category: "science",
  },
  {
    id: 20,
    question: "Which vitamin is produced in the skin with the help of sunlight ?",
    options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"],
    correctAnswer: 4,
    explanation: "Essential for strong bones and calcium absorption .",
    category: "science",
  },
  {
    id: 21,
    question: "Which is unit is used to measure electric current ?",
    options: ["Volt", "Ampere", "Watt", "Ohm"],
    correctAnswer: 2,
    explanation: "Named after Andre-Marie Ampere, it measures current flow.",
    category: "science",
  },
  {
    id: 22,
    question: "Which of the following is a high-level programming language ?",
    options: ["Assembly language", "Python", "Machine code", "Binary"],
    correctAnswer: 2,
    explanation: "High-level languages are human-readable and closer to natural language.",
    category: "technology",
  },
  {
    id: 23,
    question: "Which programming language is mainly used for iOS app development ?",
    options: ["Java","C#", "Swift",  "Kotlin"],
    correctAnswer: 3,
    explanation: "Swift is Apple's official language for iOS and macOS apps.",
    category: "technology",
  },
  {
    id: 24,
    question: "Who is Known as the `Iron Man of India`?",
    options: ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Chandra Bose","Sardar Vallabhbhai Patel",],
    correctAnswer: 4,
    explanation: "He played a key role in uniting princely states into independent India.",
    category: "history",
  },
  {
    id: 25,
    question: "The French Revolution began in which year ?",
    options: ["1757", "1789", "1804", "1815"],
    correctAnswer: 2,
    explanation: "It marked the rise of democracy and fall of monorchy in France.",
    category: "history",
  },
    {
    id: 26,
    question: "Who is the first Emperor of the Maurya Dynasty in India ?",
    options: ["Ashoka", "Bindusara", "Harsha", "Chandragupta Maurya"],
    correctAnswer: 4,
    explanation: "He foumded the Maurya Empire in 321 BCE with help from Chanakya.",
    category: "history",
  },
    {
    id: 27,
    question: "In which year did World War 2 end ?",
    options: ["1945", "1940", "1950", "1939"],
    correctAnswer: 1,
    explanation: "WW2 ended in 1945 with the defeat of Germany and Japan.",
    category: "history",
  },
    {
    id: 28,
    question: "The Great Wall of china was mainly built to protect against which group ?",
    options: ["Mongols", "Japanese", "Perians", "Indians"],
    correctAnswer: 1,
    explanation: "It was built to prevent invasions from northern nomadic tribes.",
    category: "history",
  },
  {
    id: 29,
    question: "Who is gave the slogen `Swaraj is my brithright, and i shall have it`",
    options: ["Lala Lajpat Rai","Bal Gangadhar tilak", "Bhagat singh", "Mahatma Gandhi",],
    correctAnswer: 2,
    explanation: "Tilak was one of the leaders of the Indian freedom movement.",
    category: "history",
  },
  {
    id: 30,
    question: "Which one the following Rigvedic rivers is identified with the morden Ravi?",
    options: ["Vipasha", "Purushni", "Asikni", "Vipas"],
    correctAnswer: 1,
    explanation: "The Rigvadic Purushni is identified with morden Ravi river.",
    category: "history",
  },
  {
    id: 31,
    question: "The world's oldest university,`Nalanda University,` is located in which country ?",
    options: ["China", "India", "Greece", "Iran"],
    correctAnswer: 1,
    explanation: "Founded in the 5th century CE in Biahr Nalanda attracted scholars from across Asia.",
    category: "history",
  },
  {
    id: 32,
    question: " Which civilization is credited with the invention of the wheel?",
    options: ["Indus Valley Civilization", "Egyptian Civilization", "Mesopotamian Civilization", "Chinese Civilization"],
    correctAnswer: 1,
    explanation: " The earliest evidence of the wheel comes from Mesopotamia(around 3500 BCE).",
    category: "history",
  },
  {
    id: 33,
    question: "Which is the world's largest non-polar desert ?",
    options: ["Sahara", "Gobi", "Klahari", "Atacama"],
    correctAnswer: 1,
    explanation: "Sahara Desert in Africa covers ~9.2 million sq km, the largest hot desert in the world.",
    category: "geography",
  },
  {
    id: 34,
    question: "The Tropic of Capricorn Passes through How many countries?",
    options: ["8", "14", "10", "12"],
    correctAnswer: 3,
    explanation: "It crosses 10 countries including - Brazil,Namibia,Chile,Paraguay,Argentina,Botswana, South Africa,Mozambique,Australia,Madagascar.",
    category: "geography",
  },
  {
    id: 35,
    question: "Mount Kilimanjaro, the highest mountain in Africa, is located in which country ?",
    options: ["Kenya", "Uganda", "Tanzania", "Ethiopia"],
    correctAnswer: 3,
    explanation: "Kilimanjaro rises ~5.895 m, a dormant valcanic peak.",
    category: "geography",
  },
  {
    id: 36,
    question: "The term `Ring of Fire` refers to which region ?",
    options: ["Himalayan Belt", "Mediterranean Coast", "Atlantic Ocean basin","Pacific Ocean basin", ],
    correctAnswer: 4,
    explanation: "It's an area pf frequent earthquakes and volcanic erupions encircling the Pacific Ocean.",
    category: "geography",
  },
  {
    id: 37,
    question: "Which is the largest delta in the world ?",
    options: ["Nile Delta", "Amazon Delta", "Ganga-Brahmaputra Delta", "Mekong Delta"],
    correctAnswer: 3,
    explanation: "Located in India and Bangladesh, covring ~105,000sq km, it's called the Sunderbans Delta.",
    category: "geography",
  },
  {
    id: 38,
    question: "Which river is known as `Sorrow of Bengal` due to frequent floods ?",
    options: ["Brahmaputra", "Ganga", "Damodar", "Kosi"],
    correctAnswer: 4,
    explanation: "Originates from Nepal, frequntly floods North Bihar, earning the nickname.",
    category: "geography",
  },
  {
    id: 39,
    question: "Which country has the World's longest coastline ?",
    options: ["Canada", "Australia", "Russia", "USA"],
    correctAnswer: 1,
    explanation: "Canada has ~202,080 km of coastline, the longest in the world, because of its Arctic islands and bays.",
    category: "geography",
  },
  {
    id: 40,
    question: "The Great Rift Vally is located in which continent ?",
    options: ["Asia", "Africa", "South America", "Australia"],
    correctAnswer: 2,
    explanation: "Extends from the Red Sea down through East Africa; formed by tecttonic plate movements.",
    category: "geography",
  },
  {
    id: 41,
    question: "The capital of Australia ?",
    options: ["Sydny", "Melbourne", "Perth", "Canberra"],
    correctAnswer: 4,
    explanation: "Many think sydney or Melbourne, but Canerra was chosen in 1908 as a compromise between Sydney and Melbourne.",
    category: "general",
  },
   {
    id: 42,
    question: " Who wrote the book Arthashastra?",
    options: ["Kalidasa", "Kautilya", "Panini", "Banabhatta"],
    correctAnswer: 2,
    explanation: "Arthashastra is an ancient Indian treatise on ststecrft,econimics and military strategy written by Kautilya during the Maurya period.",
    category: "general",
  },
   {
    id: 43,
    question: "Who was the first person to reach thre South Pole?",
    options: ["Robert Scott", "Roald Amundsen", "Edmund Hillary", "James Cook"],
    correctAnswer: 2,
    explanation: " .",
    category: "general",
  },
   {
    id: 44,
    question: " First battle of Panipat (1526) was fought between?",
    options: ["Babur and Ibrahim Lodi","Akbar and Rana Sanga", "Sher Shah and Humayun", "Bahlol Lodi and Sikandar Lodi"],
    correctAnswer: 1,
    explanation: "The First Battle of Panipat in 1526 marked the beginning of the Maghal Empire in India when Babur defeated Ibrahim Lodi with advanced artillery.",
    category: "general",
  },
   {
    id: 45,
    question: "The deepest point on Earth is ?",
    options: ["Tongo Trench", "Mariana Trench", "Philippine Trench", "Java Trench"],
    correctAnswer: 2,
    explanation: "The Mariana Trench in the Pacific Ocean has the Challenger Deep, about 11,034 meters(26,201ft) below sea level, making it the Earth's deepest known point.",
    category: "general",
  },
   {
    id: 46,
    question: "Which Indian scientist won the Nobel Prize in Physics in 1930?",
    options: ["C. V. Raman", "Homi J. Bhabha", "Meghnad Saha", "Satyendra Nath Bose"],
    correctAnswer: 1,
    explanation: "Sir C. V. Raman received the Nobel Prize in Physics in 1930 for his discovery of the Raman Effect(scattering of light).",
    category: "general",
  },
   {
    id: 47,
    question: "In which year did the French Revolution begin?",
    options: ["1776", "1804", "1815","1789"],
    correctAnswer: 4,
    explanation: "The French Revolution began in 1789 with the storming of the Bastille, leading to the overthrow of monarchy and rise of democracy.",
    category: "general",
  },
   {
    id: 48,
    question: "Who ua the first Governor-General of independent India ?",
    options: ["C.Rajagopalachari", "Dr. Rajendra Prasad", "Lord Mountbatten", "Jawaharlal Nehru"],
    correctAnswer: 3,
    explanation: "Lord Mountbatten was the last British Viceroy an Become the First Governer-General of Independant India(1947-1948).",
    category: "general",
  },
   {
    id: 49,
    question: "The currency of Brazil is ?",
    options: ["Peso", "Real", "Doller", "Cruzeiro"],
    correctAnswer: 2,
    explanation: "The official currency of Brazil is the Brazilian Real(plural: Reais), introduced in 1994 to control inflation.",
    category: "general",
  },
   {
    id: 50,
    question: "Which country hosted the first morden Olympic Games(1896) ?",
    options: ["France", "Italy", "Greece", "USA"],
    correctAnswer: 2,
    explanation: "The first morden Olympics were held in Athens, Greece, in 1896, reviving the ancient tradition.",
    category: "general",
  },
  
]
